set(SourceFiles
    SOURCE/PluginEditor.cpp
    SOURCE/PluginEditor.h
    SOURCE/PluginProcessor.cpp
    SOURCE/PluginProcessor.h
    SOURCE/PyramidBlock.cpp
    SOURCE/PyramidBlock.h
    SOURCE/PyramidView.cpp
    SOURCE/PyramidView.h
    SOURCE/Util/Juce_Header.h
)